apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  selector:
    app: logstash
  type: ClusterIP
  clusterIP: 10.0.37.118
  ports:
  - name: beats
    port: 5044
    protocol: TCP
    targetPort: beats
