apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  serviceName: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        env:
        - name: HTTP_HOST
          value: 0.0.0.0
        - name: HTTP_PORT
          value: "9600"
        - name: ELASTICSEARCH_HOST
          value: quickstart-es-http.default
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: LS_JAVA_OPTS
          value: -Xmx1g -Xms1g
        - name: CONFIG_RELOAD_AUTOMATIC
          value: "true"
        - name: PATH_CONFIG
          value: /usr/share/logstash/pipeline
        - name: PATH_DATA
          value: /usr/share/logstash/data
        - name: QUEUE_CHECKPOINT_WRITES
          value: "1"
        - name: QUEUE_DRAIN
          value: "true"
        - name: QUEUE_MAX_BYTES
          value: 1gb
        - name: QUEUE_TYPE
          value: persisted
        image: docker.elastic.co/logstash/logstash-oss:7.1.1
        ports:
        - containerPort: 9600
          name: monitor
          protocol: TCP
        - containerPort: 5044
          name: beats
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /mnt/certs/
          name: quickstart-es-http-certs-public # ------------------------------------------------
          readOnly: true
      serviceAccount: logstash
      serviceAccountName: logstash
      volumes:
      - configMap:
          defaultMode: 420
          name: logstash-patterns
        name: patterns
      - configMap:
          defaultMode: 420
          name: logstash-files
        name: files
      - configMap:
          defaultMode: 420
          name: logstash-pipeline
        name: pipeline
      - name: quickstart-es-http-certs-public # ---------------------------------------
        secret:
          defaultMode: 420
          optional: false
          secretName: quickstart-es-http-certs-public
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      volumeMode: Filesystem
